### ISSUE TITLE
Ajouter une carte sur la page Lieux

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2015#10]
Carte Mapbox en cours de réalisation

```html 
<iframe width='100%' height='500px' frameBorder='0' src='https://a.tiles.mapbox.com/v4/sudweb.l4akmo22/attribution,zoompan,zoomwheel,geocoder,share.html?access_token=pk.eyJ1Ijoic3Vkd2ViIiwiYSI6IkhmcGZDVjgifQ.G_2G6SN8Ylfl7md8vJBaog'></iframe>
```

**Comment by DirtyF** [comment]
@oncletom je viens de tester l'insertion et j'ai toujours le message de notification de dépassement, bizarre car les stats sur le site de MapBox indique 0 affichages.
```
{"message":"Account over limit."}
```

**Comment by oncletom** [comment]
@DirtyF pourtant quand j'ouvre la `src` dans mon navigateur, aucune erreur. Et toi ?

**Comment by DirtyF** [comment]
Rien non plus.
J'ai testé avec l'exemple en JS donné sur la doc de leur API et rien non plus. 
On peut passer par OpenStreetMap en attendant de contacter leur support.

**Comment by oncletom** [comment]
Je ne comprends pas le 'rien non plus' : rien = l'erreur mentionée initialement n'apparait plus ou 'rien' = rien ne s'affiche car tu as le message de notification de dépassement ?
