### ISSUE TITLE
Design refresh

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2015#23]
- [ ] Générer un style guide
 
![mood-board](https://cloud.githubusercontent.com/assets/103008/6218773/3a57fad2-b622-11e4-831f-3e0f0f605548.jpg)

**Comment by DirtyF** [comment]
@oncletom on utiliserait pas un plugin grunt pour ça : https://github.com/indieisaconcept/grunt-styleguide ?

**Comment by oncletom** [comment]
Hey why not ! Jamais utilisé mais bonne idée :-)
