### ISSUE TITLE
Unable to push to master

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2015#38]
@oncletom je capte pas pourquoi j'arrive pas à pousser les derniers commits sur la branche protégée `master` à cause de Travis, du coup ça crée des 404 sur les liens vers les slides hébergés sur notre serveur car ça déploie bien sur la branche `gh-pages`, on a les liens mais pas les fichiers. 

Exemple : http://sudweb.fr/2015/slides/02-Ste%CC%81phanie-Vidal.pdf

Voici le message que me retourne Github Desktop quand j'appuie sur le bouton `sync` :

```
GH006: Protected branch update failed for refs/heads/master.        
Required status check "continuous-integration/travis-ci" is expected        
```

Voici ce que me retourne un simple `git push` depuis la ligne de commande : 

````
Username for 'https://github.com': DirtyF
Password for 'https://DirtyF@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sudweb/2015.git/'
```

**Comment by oncletom** [comment]
Je pensais que la protection empêchait les *force push* — visiblement ça concerne tous les push, ceux dont les tests Travis ne sont pas verts.

Je vais enlever la protection - c'était pour encourager les PR et surtout éviter les *force push*.

Par contre si tu peux pousser vers gh-pages, il n'y a pas de raison que les slides n'y soient pas (t'as pensé à les ajouter au versionning ?)

**Comment by DirtyF** [comment]
En effet en virant la protection, je peux pousser, je capte pas pourquoi Travis passe pas, mais on peut remettre la protection de la branche master pour inciter au PR, c'est une bonne pratique.
