### ISSUE TITLE
Lien vers le blog en 404

### ISSUE THREAD

**Issue by Natouille** [sudweb/2015#41]
En bas de page, le lien http://sudweb.fr/blog/category/2015/ est en 404

**Comment by oncletom** [comment]
C'est ma faute : j'ai passé le blog en site statique et je crois que j'ai pas activé les catégories.

> https://github.com/sudweb/blog

C'est un blog Jekyll donc ça doit pas être compliqué à faire.

**Comment by oncletom** [comment]
Ayé, en ligne via sudweb/blog@7d203f3a49a79810ec48e992eca03d3d3b17e195 :-)
