### ISSUE TITLE
Préciser le numéro d'agrément

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2015#9]
Notre numéro d'agrément de formation ne change pas c'est toujours le 91.34.06.975

En complément : 

Après c’est chaque société qui décide de faire passer la prise en charge soit par le plan de formation, soit par le CPF.

Les formations « gestion de projets » rentrent dans le cadre des formations éligibles au CPF

**Comment by oncletom** [comment]
À rajouter en `.callout` sur la page inscriptions I suppose :-)

**Comment by DirtyF** [comment]
On verra, pour le moment j'attends plus d'infos de la part de notre organisme de formation, comme le numéro de formation CFP à indiquer.
